quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/sistema_advocacia?useSSL=false&serverTimezone=UTC

quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.database.version-check.enabled=false

smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=sistema-advocacia
smallrye.jwt.new-token.lifespan=86400

quarkus.smallrye-jwt.enabled=true

quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=BearerAuth
quarkus.smallrye-openapi.security-scheme-description=Cole apenas o token JWT (sem a palavra Bearer)
quarkus.swagger-ui.always-include=true

quarkus.log.level=INFO
quarkus.log.category."com.advocacia".level=DEBUG
quarkus.smallrye-openapi.info-title=Sistema Advocacia API - Área do Cliente